### ISSUE TITLE
invalid constant type Error

### ISSUE THREAD

**Issue by sayyad84** [QuiltMC/quiltflower#189]
Hi,
Your product has performed very well among the available options, but there are some problems when using it, which I request you to check and fix. like the:
`INFO:  Decompiling class com/adventnet/client/components/table/pdf/PropertySheetRenderer
WARN:        Method getDollarReqParams (Ljava/lang/String;Lcom/adventnet/client/view/web/ViewContext;)Ljava/lang/String; in class com/adventnet/client/components/table/template/FillTable couldn't be written.
java.lang.RuntimeException: invalid constant type: Ljava/lang/Object;
        at org.jetbrains.java.decompiler.modules.decompiler.exps.ConstExprent.toJava(ConstExprent.java:347)
        at org.jetbrains.java.decompiler.modules.decompiler.exps.AssignmentExprent.toJava(AssignmentExprent.java:146)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.listToJava(ExprProcessor.java:858)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.BasicBlockStatement.toJava(BasicBlockStatement.java:65)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.IfStatement.toJava(IfStatement.java:199)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.jmpWrapper(ExprProcessor.java:796)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.SequenceStatement.toJava(SequenceStatement.java:111)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.jmpWrapper(ExprProcessor.java:796)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.CatchStatement.toJava(CatchStatement.java:178)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:37)
        at org.jetbrains.java.decompiler.main.ClassWriter.methodToJava(ClassWriter.java:1084)
        at org.jetbrains.java.decompiler.main.ClassWriter.classToJava(ClassWriter.java:334)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:480)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:156)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$0(ContextUnit.java:179)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
`

**Comment by sayyad84** [comment]
[DefaultTransformer.zip](https://github.com/QuiltMC/quiltflower/files/9289372/DefaultTransformer.zip)
and in this file.

**Comment by SuperCoder7979** [comment]
Hey, I deleted the attached class files as I wasn't sure if they were copyright materials or not. However, the described issue is known and will be fixed soon.

**Comment by sayyad84** [comment]
Thank you
I have tried many products but your product has better output than all of them but I need to fix this problem to move forward with my project. How long do you think it will take to fix this problem?

**Comment by SuperCoder7979** [comment]
I'm not quite sure, but I will make sure to prioritize it. The next release (1.9.0) will come out over the next few months, but I'll make sure to update you here when it's fixed so that you can build the current dev tree from source if you wish.

**Comment by sayyad84** [comment]
I am not very professional in Java language. I am planning to add a local calendar to an application to be used in our company, so I need access to the application code.
Is it possible to guide me how to use decompiler source code?

**Comment by SuperCoder7979** [comment]
You would just need to clone this repository and do `./gradlew.bat build`. The resulting jar will be in the `build/libs` folder.

**Comment by SuperCoder7979** [comment]
This issue should be resolved now, you can try building from the branch as I stated above and using that jar. If that doesn't work, please let me know.

**Comment by sayyad84** [comment]
Hi,
I checked the new version of the QuiltFlower 1.9 and this problem is still there but this problem is not present in the new version and previous versions of Fernflower.
